kind: Deployment
apiVersion: apps/v1
metadata:
  name: memorybox-external
  labels:
    app: memorybox-external
spec:
  selector:
    matchLabels:
      app: memorybox-external
  replicas: 1
  template:
    metadata:
      name: memorybox-external
      labels:
        app: memorybox-external
    spec:
      containers:
        - name: memberbox-external
          image: docker.io/hyeonkyo/memorybox-external:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: port1
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi
---

kind: ConfigMap
apiVersion: v1
metadata:
  name: memorybox
  namespace: ikujo
data:
  DB_SERVER: mysql
  DB_PORT: "3306"
  DB_NAME: "memory_box"

---

kind: Secret
apiVersion: v1
metadata:
  name: memorybox
  namespace: ikujo
type: Opaque
data:
  DB_USERNAME: aWt1am8=
  DB_PASSWORD: Mmt1ajAh
---

apiVersion: v1
kind: Service
metadata:
  name: memorybox-external
spec:
  type: ClusterIP
  selector:
    app: memorybox-external
  ports:
    - name: memorybox-external
      port: 8080
      targetPort: 8080
